### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by mswSoftArts** [dsheiko/bycontract#1]
"bycontract" looks really great and is a real gapfiller! Under which licence do you distribute your library? Thank you for sharing!

**Comment by dsheiko** [comment]
It's MIT(http://mit-license.org/) and set in `package.json`. Just fixed the link to the license details.

**Comment by mswSoftArts** [comment]
Your work saves valuable development time. Thank you very much!

**Comment by OmgImAlexis** [comment]
@dsheiko can you please update your license to use the new format? Right now npm is showing it as "none".

https://docs.npmjs.com/files/package.json#license

![Screen Shot 2019-09-08 at 1 18 58 pm](https://user-images.githubusercontent.com/6525926/64483033-29efde00-d23b-11e9-848f-58a2839ae184.png)

**Comment by dsheiko** [comment]
Thank you, done
