### ISSUE TITLE
Confusing documentation

### ISSUE THREAD

**Issue by gbkwiatt** [dsheiko/bycontract#14]
I am sorry, but documentation is super confusing. 

I just want to implement simple validation for object passed. 

```JS
export const requestCreateService = async (payload) => {
  console.log(payload,arguments)
  const payloadType = {
    title: 'string',
    body: 'string',
    createdBy: 'string',
    categoryID: 'number',
    priority: 'string=',
    files: 'array=',
  }
  validate(arguments, [payloadType])
}
```

that does not work, because essentially, `arguments` has loads of other objects not just payload. 

How can I point so it does check only payload object ? also ideally how can I check if payload was passed at all ?

**Comment by nikolaytsigvintsev** [comment]
Hello @gbkwiatt !

It works for me if validate(payload, payloadType)
